#Randy Jackson
#11/30/23
#CTI_110
#A program that calculates statistics of floats values given by the user

#Get four float values from user by, using the input function
#Create four variables to store the four different float values

float_value_1 = float(input("Enter first float value here:  "))
float_value_2 = float(input("Enter second float value here:  "))
float_value_3 = float(input("Enter third value float value here:  "))
float_value_4 = float(input("Enter fourth float value here:  "))


#creat variable to store the product of all float values
product_of_all_values = print(float_value_1 * float_value_2 * float_value_3 * float_value_4)

#create varibale to hold the average of all the float values

average = product_of_all_values 

print(f'{product_of_all_values}')

print(f'{average}')

